export const CLASSES_LOADING = "CLASSES_LOADING";
export const CLASSES_FAILED = "CLASSES_FAILED";
export const ADD_CLASSES = "ADD_CLASSES";

export const CLASSINFO_LOADING = "CLASSINFO_LOADING";
export const CLASSINFO_FAILED = "CLASSINFO_FAILED";
export const ADD_CLASSINFO = "ADD_CLASSINFO";

export const POST_COMMENT = "POST_COMMENT";
export const LOAD_COMMENTS = "LOAD_COMMENTS";
export const COMMENTS_FAILED = "COMMENTS_FAILED";
export const ADD_COMMENTS = "ADD_COMMENTS";
export const ADD_NEW_COMMENT = "ADD_NEW_COMMENT";

export const ARTICLES_LOADING = "ARTICLES_LOADING";
export const ARTICLES_FAILED = "ARTICLES_FAILED";
export const ADD_ARTICLES = "ADD_ARTICLES"

export const CAROUSEL_LOADING = "CAROUSEL_LOADING";
export const CAROUSEL_FAILED = "CAROUSEL_FAILED";
export const ADD_CAROUSEL = "ADD_CAROUSEL";
export const ADD_CAROUSEL_IMAGE = "ADD_CAROUSEL_IMAGES";
export const CAROUSEL_IMAGES_LOADING = "CAROUSEL_IMAGES_LOADING";
export const CAROUSEL_IMAGES_FAILED = "CAROUSEL_IMAGES_FAILED";

export const ADD_FAVORITE_CLASS = "ADD_FAVORITE_CLASS";
export const DELETE_FAVORITE_CLASS = 'DELETE_FAVORITE_CLASS';
export const ADD_FAVORITE_ARTICLE = "ADD_FAVORITE_ARTICLE";
export const DELETE_FAVORITE_ARTICLE = 'DELETE_FAVORITE_ARTICLE';

export const POST_SIGN_UP = "POST_SIGN_UP";
